// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4VhM73barj2z6DQHAHFbtGYSlXs8psoQ',
    appId: '1:292064773846:web:02012e6a1ab0700d83eb77',
    messagingSenderId: '292064773846',
    projectId: 'job-app-d8492',
    authDomain: 'job-app-d8492.firebaseapp.com',
    storageBucket: 'job-app-d8492.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl9CEP4qly4QXdna6tklb6NTgO4KAUZYw',
    appId: '1:292064773846:android:33bb4e384617910483eb77',
    messagingSenderId: '292064773846',
    projectId: 'job-app-d8492',
    storageBucket: 'job-app-d8492.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk7jIg0dcL7fg5MFsCf3rG4_e1KQq2suo',
    appId: '1:292064773846:ios:e21353249bdd1f0d83eb77',
    messagingSenderId: '292064773846',
    projectId: 'job-app-d8492',
    storageBucket: 'job-app-d8492.appspot.com',
    iosBundleId: 'com.example.jobApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk7jIg0dcL7fg5MFsCf3rG4_e1KQq2suo',
    appId: '1:292064773846:ios:666638c743c48dac83eb77',
    messagingSenderId: '292064773846',
    projectId: 'job-app-d8492',
    storageBucket: 'job-app-d8492.appspot.com',
    iosBundleId: 'com.example.jobApp.RunnerTests',
  );
}
